# .gitlab-ci.yml – multi-container mono-repo
# runner dind
# Structure:
#   Containers/<name>/Dockerfile
#
# Each container is pushed to:
#   $CI_REGISTRY_IMAGE/<name>:latest
#   $CI_REGISTRY_IMAGE/<name>:<commit-sha>

image: docker:20.10

services:
  - name: docker:dind
    alias: docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

.build_template:
  stage: build
  tags:
    - dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - >
      docker build
      -t "$CI_REGISTRY_IMAGE/$CONTAINER_NAME:$CI_COMMIT_SHA"
      -t "$CI_REGISTRY_IMAGE/$CONTAINER_NAME:latest"
      "Containers/$CONTAINER_NAME"
    - docker push "$CI_REGISTRY_IMAGE/$CONTAINER_NAME:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/$CONTAINER_NAME:latest"

build_cpc2:
  extends: .build_template
  variables:
    CONTAINER_NAME: cpc2
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - changes:
        - Containers/cpc2/**/*

build_ncrna-mirna:
  extends: .build_template
  variables:
    CONTAINER_NAME: ncrna-mirna
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - changes:
        - Containers/ncrna-mirna/**/*

build_star:
  extends: .build_template
  variables:
    CONTAINER_NAME: star
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - changes:
        - Containers/star/**/*

build_ensembl-genes:
  extends: .build_template
  variables:
    CONTAINER_NAME: ensembl-genes
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - changes:
        - Containers/ensembl-genes/*

build_ensembl-genes-qc-dev:
  extends: .build_template
  variables:
    CONTAINER_NAME: ensembl-genes-qc-dev
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - changes:
        - Containers/ensembl-genes-qc-dev/*

build_mirmachine_dev:
  extends: .build_template
  variables:
    CONTAINER_NAME: mirmachine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - changes:
        - Containers/mirmachine/*

build_omark:
  extends: .build_template
  variables:
    CONTAINER_NAME: omark
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - changes:
        - Containers/omark/*

build_choros:
  extends: .build_template
  variables:
    CONTAINER_NAME: choros
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - changes:
        - Containers/choros/**/*
