name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main
      # Add other branches if needed
      # - dev

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    
    steps:
          
      - name: Trigger GitLab
        run: |
          RESPONSE=$(curl \
            --silent \
            --show-error \
            --write-out "\nHTTP_STATUS:%{http_code}\n" \
            --request POST \
            --form token="${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
            --form ref="${{ github.ref_name }}" \
            "https://gitlab.ebi.ac.uk/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline")
      
          echo "$RESPONSE"
